<?php

/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

namespace ThieleUndKlose\Autotranslate\ContextMenu;

use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Core\Utility\PathUtility;
use TYPO3\CMS\Core\Information\Typo3Version;
use TYPO3\CMS\Backend\ContextMenu\ItemProviders\AbstractProvider;
use TYPO3\CMS\Backend\Utility\BackendUtility;
use ThieleUndKlose\Autotranslate\Utility\TranslationHelper;

/**
 * Item provider adding Hello World item
 */
class AutotranslateItemProvider extends AbstractProvider
{
    /**
     * @var array<string, mixed>
     */
    protected array $record = [];

    /**
     * This array contains configuration for items you want to add
     * @var array<string, array<string, string>>
     */
    protected $itemsConfiguration = [
        'autotranslatePage' => [
            'type' => 'item',
            'label' => 'LLL:EXT:autotranslate/Resources/Private/Language/locallang_mod.xlf:record_translation.button',
            'iconIdentifier' => 'autotranslate-extension-v14',
            'callbackAction' => 'triggerRecordTranslation',
        ],
    ];

    /**
     * Checks if this provider may be called to provide the list of context menu items for given table.
     */
    public function canHandle(): bool
    {
        // Current table is: $this->table
        // Current UID is: $this->identifier
        // return $this->table === 'pages';
        // DebuggerUtility::var_dump($this->table);

        // abort for localized items
        $this->record = BackendUtility::getRecordWSOL($this->table, (int)$this->identifier) ?: [];
        if ((int)($this->record['sys_language_uid'] ?? 0) !== 0)
            return false;

        $siteConfiguration = TranslationHelper::siteConfigurationValue($this->resolvePageId());
        if (!is_array($siteConfiguration)) {
            return false;
        }

        if (TranslationHelper::translationSettingsDefaults($siteConfiguration, $this->table) === null) {
            return false;
        }

        if (TranslationHelper::possibleTranslationLanguages($siteConfiguration['languages'] ?? []) === []) {
            return false;
        }

        return true;
    }

    /**
     * Returns the provider priority which is used for determining the order in which providers are processing items
     * to the result array. Highest priority means provider is evaluated first.
     *
     * This item provider should be called after PageProvider which has priority 100.
     *
     * BEWARE: Returned priority should logically not clash with another provider.
     *         Please check @see \TYPO3\CMS\Backend\ContextMenu\ContextMenu::getAvailableProviders() if needed.
     */
    public function getPriority(): int
    {
        return 55;
    }

    /**
     * Registers the additional JavaScript ES6 callback-module which will allow to display a notification
     * whenever the user tries to click on the "Hello World" item.
     * The method is called from AbstractProvider::prepareItems() for each context menu item.
     * @return array<string, string>
     */
    protected function getAdditionalAttributes(string $itemName): array
    {
        return [
            // Legacy fallback for TYPO3 v12 only. Remove once v12 support is dropped.
            'data-callback-module' => (new Typo3Version())->getMajorVersion() <= 12
                ? $this->getLegacyCallbackModulePath()
                : '@thieleundklose/autotranslate/context-menu-actions',
            // Here you can also add any other useful "data-" attribute you'd like to use in your JavaScript (e.g. localized messages)
        ];
    }

    /**
     * This method adds custom item to list of items generated by item providers with higher priority value (PageProvider)
     * You could also modify existing items here.
     * The new item is added after the 'info' item.
     * @param array<string, mixed> $items
     * @return array<string, mixed>
     */
    public function addItems(array $items): array
    {
        $this->initDisabledItems();
        // renders an item based on the configuration from $this->itemsConfiguration
        $localItems = $this->prepareItems($this->itemsConfiguration);

        if (!isset($items['info'])) {
            // pass items to the next provider
            return $items + $localItems;
        }
        //finds a position of the item after which 'hello' item should be added
        $position = array_search('info', array_keys($items), true);

        if ($position === false) {
            return $items + $localItems;
        }
        //slices array into two parts
        $beginning = array_slice($items, 0, $position + 1, true);
        $end = array_slice($items, $position, null, true);

        // adds custom item in the correct position
        return $beginning + $localItems + $end;
    }

    /**
     * This method is called for each item this provider adds and checks if given item can be added
     */
    protected function canRender(string $itemName, string $type): bool
    {
        // checking if item is disabled through TSConfig
        if (in_array($itemName, $this->disabledItems, true)) {
            return false;
        }
        $canRender = false;
        switch ($itemName) {
            case 'autotranslatePage':
                $canRender = $this->canSayHello();
                break;
        }
        return $canRender;
    }

    /**
     * Helper method implementing e.g. access check for certain item
     */
    protected function canSayHello(): bool
    {
        //usually here you can find more sophisticated condition. See e.g. PageProvider::canBeEdited()
        return true;
    }

    private function resolvePageId(): int
    {
        if ($this->table === 'pages') {
            return (int)($this->record['uid'] ?? 0);
        }

        return (int)($this->record['pid'] ?? 0);
    }

    /**
     * Legacy callback-module path for TYPO3 v12.
     * Keep this only until v12 support is removed.
     */
    private function getLegacyCallbackModulePath(): string
    {
        $absoluteFilePath = GeneralUtility::getFileAbsFileName(
            'EXT:autotranslate/Resources/Public/JavaScript/context-menu-actions.js'
        );

        return preg_replace(
            '/\.js$/',
            '',
            PathUtility::getAbsoluteWebPath($absoluteFilePath)
        ) ?: '';
    }
}
