services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ThieleUndKlose\Autotranslate\:
    resource: '../Classes/*'

  ThieleUndKlose\Autotranslate\Command\BatchTranslation:
    tags:
      - name: console.command
        command: "autotranslate:batch:run"
        description: "Command for automatic translation of a number of elements."

  ThieleUndKlose\Autotranslate\TsConfig\Loader:
    public: true
    tags:
      - name: event.listener
        identifier: 'add-page-configuration'
        event: TYPO3\CMS\Core\TypoScript\IncludeTree\Event\ModifyLoadedPageTsConfigEvent
        method: 'addPageConfiguration'

  ThieleUndKlose\Autotranslate\Backend\RecordList\RecordTranslationActionListener:
    tags:
      - name: event.listener
        identifier: 'autotranslate-record-list-action-listener'
        event: TYPO3\CMS\Backend\RecordList\Event\ModifyRecordListRecordActionsEvent

  ThieleUndKlose\Autotranslate\Backend\GlobalJavaScript\RecordTranslationJavaScriptListener:
    tags:
      - name: event.listener
        identifier: 'autotranslate-backend-javascript-listener'
        event: TYPO3\CMS\Backend\Controller\Event\AfterBackendPageRenderEvent
